src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $order_number = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Menu::class, mappedBy: 'orders')]
    private Collection $menus;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderNumber(): ?string
    {
        return $this->order_number;
    }

    public function setOrderNumber(string $order_number): self
    {
        $this->order_number = $order_number;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Menu>
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus->add($menu);
            $menu->addOrder($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->removeElement($menu)) {
            $menu->removeOrder($this);
        }

        return $this;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Menu;
use App\Entity\Order;
use App\Entity\Restaurant;
use App\Repository\OrderRepository;
use App\Services\CalcPriceService;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use function PHPUnit\Framework\throwException;

class OrderController extends AbstractController
{
    public function __construct(
        private OrderRepository $orderRepository,
        private EntityManagerInterface $em,
        private CalcPriceService $calcPriceService
    ) {
        # code...
    }


    #[Route('/orders', name: 'orders')]
    public function index(): Response
    {
        $orders = $this->orderRepository->findAll();
        return $this->render('order/index.html.twig', [
            'orders' => $orders
        ]);
    }
    #[Route('/orders/{id}', name: 'order_creation')]
    public function create(Menu $menu, Request $request): Response
    {
        $order = new Order();

        if ($request->getMethod() == Request::METHOD_POST) {
            // if ($request->get('menuId') == $menu->getId()) {
            $order->setCreatedAt(new DateTimeImmutable());
            $order->setOrderNumber(rand(1, 1200) . '-' . substr($menu->getName(), 0, 3) . '-' . $menu->getId());
            $order->addMenu($menu);
            $order->setPrice($menu->getPrice());
            $order->setStatus('created');
            $order->setUser($this->getUser());
            $this->em->persist($order);
            $this->em->flush();

            return $this->redirectToRoute('order_recap', ['id' => $order->getId()]);
            // }
        } else {
            throw new Exception('Page does not exist');
        }
    }

    #[Route('/order/{id}', name: 'order_recap')]
    public function order_recap(Order $order): Response
    {
        $percentage = 0.1;
        $percentage = $this->calcPriceService->calcPecentage($order->getPrice(), $percentage);
        $finalPrice = $this->calcPriceService->calcPrice($order->getPrice(), $percentage);
        return $this->render('order/details.html.twig', [
            'order' => $order,
            'percentage' => $percentage,
            'finalPrice' => $finalPrice
        ]);
    }
}

templates/order/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Order
{% endblock %}

{% block body %}

	<h1>Your Order</h1>


	<div class="order">

		<table class="table col-6">
			<tbody>
				<tr>
					<th scope="row">
						<h5 class="text-success">Menu:
						</h5>
					</th>
					<td>
						<h5 class="text-success">{{order.menus[0].name}}</h5>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<h5 class="text-success">Order number:
						</h5>
					</th>
					<td>
						<h5 class="text-success">{{order.orderNumber}}</h5>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<h5 class="text-success">Creation:
						</h5>
					</th>
					<td>
						<h5 class="text-success">{{order.createdAt|date('d/m/y')}}</h5>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<h5 class="text-white">Status:
						</h5>
					</th>
					<td>
						<h5 class="text-white">{{order.status}}</h5>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<h5 class="text-warning">Menu price:
						</h5>
					</th>
					<td>
						<h5 class="text-warning">${{order.price}}</h5>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<h5 class="text-warning">Tax
						</h5>
					</th>
					<td>
						<h5 class="text-warning">${{percentage}}</h5>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<h5 class="text-warning font-weight-bold">Total:
						</h5>
					</th>
					<td>
						<h5 class="text-warning font-weight-bold">
							$
							{{finalPrice}}
						</h5>
					</td>
				</tr>
			</tbody>
		</table>

		<button class="btn btn-success">Confirm order</button>

	</div>

{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders!
{% endblock %}

{% block body %}

	<h1>Orders</h1>

	<div class="orders">
		{% for order in orders %}
			<h4>Order number:
				{{order.orderNumber}}</h4>
			<h5 class="text-warning">${{order.price}}</h5>
			<h6>Creation:
				{{order.createdAt|date('d/m/y')}}</h6>
			<h6>Status:
				{{order.status}}</h6>

		{% endfor %}
	</div>

{% endblock %}